### ISSUE TITLE
Flatten quote identifiers

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#106]
We could renumber all quotes so they have consistent identifiers such as 0, 1, 2, 3 etc. People expect quote number 1 (or zero) to exist.

**Comment by rexim** [comment]
And break all the existing URLs. Sure.

**Comment by ForNeVeR** [comment]
Why not? I don't think anything relies on there URLs.

**Comment by rexim** [comment]
We have quite enough LogList links in logs. And they all will become

**Comment by rexim** [comment]
I just want to say, that it's too late Mr. @ForNeVeR. You should had thought about it when you was importing quotes from the legacy database.

**Comment by ForNeVeR** [comment]
Our users will remember these your words.
