### ISSUE TITLE
Move out of Heroku

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#113]
We should finally do this. 

This will allow us to drop Play framework and use something decent: #78 #112 

Also it will allow us to use encryption without paying $20 every month: #73

**Comment by rexim** [comment]
We may try to use http://theforeman.org/

**Comment by rexim** [comment]
The application itself is already moved and available at http://codingteam.org.ru:9000/

**Comment by ForNeVeR** [comment]
Don't forget to close all Heroku-specific tasks when closing this.

**Comment by rexim** [comment]
Fuckin' done!
