### ISSUE TITLE
Redirect after approval or decline

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#118]
- When the quote is approved, redirect to the approved quote page.
- When the quote is declined, redirect to the main page

**Comment by ForNeVeR** [comment]
Please note that this can be an alternative option to #75.

**Comment by rexim** [comment]
Oh, thanks for pointing that out! Completely forgot about this one. Btw, what's your opinion regarding this behavior? I think redirect is much useful and easier to implement. For declining we can redirect to the main page.

**Comment by ForNeVeR** [comment]
Well, redirect is completely okay. It is even more RESTful than simply rendering the same view. So I think that's a good idea.
