### ISSUE TITLE
New JSON serializer

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#123]
We may want to evaluate [jfc](https://github.com/travisbrown/jfc) JSON serializer. It looks really nice, and many times nicer that poor Play JSON support.

**Comment by rexim** [comment]
Well, we don't use "poor Play JSON support". We use upickle: https://github.com/codingteam/loglist/blame/master/project/Build.scala#L105

And you are the one who introduced this dependency. Can that jfc work both on JVM and JavaScript?

**Comment by rexim** [comment]
Oh, if we are going to use TypeScript + Finch, jfc doesn't need to work on JavaScript platform. Anyway, is it really better than upickle?

**Comment by ForNeVeR** [comment]
Disregard that, we still use Play poor JSON support: https://github.com/codingteam/loglist/blob/2e53256a5cf90e069235102d323ab626d1cebd1e/scalajvm/app/helpers/ReCaptcha.scala#L21

**Comment by ForNeVeR** [comment]
But okay, we'll need to discuss further our migration to Finch / whatever. I'll close that for now.
