### ISSUE TITLE
Hide CTOR's LogList behind Nginx

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#124]
Is depended on by #113

**Comment by rexim** [comment]
It won't be available until #126 is resolved

**Comment by ForNeVeR** [comment]
BTW we already have nginx fully set up on CTOR; you'll have to just add the corresponding configuration.

**Comment by rexim** [comment]
Yep, I know. This task is about adding a couple of lines to a text file. :)

**Comment by ForNeVeR** [comment]
That's totally okay.

**Comment by rexim** [comment]
Done! Configured server for loglist. Now if you point loglist.net domain to ctor via hosts you can have the access to the service. :)
