### ISSUE TITLE
Configure CTOR's LogList to not listen to the global

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#125]
Is depended on by #113

**Comment by ForNeVeR** [comment]
Why shouldn't it listen on 9000 port? (Well, there may be a conflict with something else on CTOR, but we should check that first. Or have you checked already?)

**Comment by ForNeVeR** [comment]
But it should listen only `127.0.0.1` and not the global net.

**Comment by rexim** [comment]
Hm... By not listening to 9000 port I meant not listening to the global. You're right. I'll rename the task.

**Comment by rexim** [comment]
Done! Modified `start-this-shit.sh` script. Now http://codingteam.org.ru:9000/ is unavailable but from the inside you can send request via `curl http://127.0.0.1:9000/`. It only remains to resolve #124 and #126 and the service will be fully available.

**Comment by ForNeVeR** [comment]
Great.
