### ISSUE TITLE
Update CAPTCHA

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#130]
After migration from Heroku domain is `loglist.net` not `www.loglist.net`. So the captcha service doesn' work because of that.

**Comment by rexim** [comment]
Hm.... Even with domain `www.loglist.net` it says `ERROR: Invalid site key`. It depends not only on the domain? It should be updated anyway

**Comment by rexim** [comment]
Also, I think it's better to do this issue after resolving #128

**Comment by ForNeVeR** [comment]
That maybe was due to the fact you set the public recaptcha key to "khooy". I've updated the recaptcha domain binding and copied the proper keys to the configuration file. Enjoy.

**Comment by rexim** [comment]
lol, completely forgot about that khooy. :) Thank you very much!
