### ISSUE TITLE
Domain name in the admin messages

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#132]
We have a small problem. Loglist seems to think he's placed on `localhost:9000`. This affects the domain name in the quote management messages (so I have to manually replace `localhost:9000` with `loglist.net` before sending the HTTP request). How could we control that?

**Comment by rexim** [comment]
I'll take a look into that.

**Comment by rexim** [comment]
Added `proxy_set_header Host loglist.net;` to Nginx config. The problem has been fixed.
