### ISSUE TITLE
Improve wording

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#137]
"3 цитат находятся на рассмотрении" is not very nice for me. I suggest "Цитат на рассмотрении: 3".

**Comment by rexim** [comment]
Маленький, но гордый цитат!

**Comment by ForNeVeR** [comment]
ацетат

**Comment by ForNeVeR** [comment]
цианакрилат

**Comment by rexim** [comment]
Verified the issue. The wording has been improved. Hence closing the issue.
