### ISSUE TITLE
Don't use Session.getDefaultInstance from JavaMail

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#143]
Usage of this method can become a potential bug in the future: [Notifications.scala](https://github.com/codingteam/loglist/blob/59c7e5ec427337b2da8ca08c165e32f41de5f6bf/scalajvm/app/helpers/Notifications.scala#L57). See [JavaMail FAQ](http://www.oracle.com/technetwork/java/faq-135477.html#getdefaultinstance) for more information.

We should use `Session.getInstance` instead.

**Comment by ForNeVeR** [comment]
(Sad) experience should've learned us that anything involving any kind of "default" in Java is pure evil.

**Comment by hagane** [comment]
Well this makes sense if you consider the original meaning of 'default' --
failing to fulfill one's obligatons. So `Session.getDefaultInstance(...)`
should be used when the system fails to provide a `Session` from
`Session.getInstance(...)` and you really need one (implying that any
`Session` should have to suffice).
