### ISSUE TITLE
LogList.net 502 Bad Gateway

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#146]
http://loglist.net/

**Comment by rexim** [comment]
Don't know how. But this is probably happened after #145. The last build was unstable http://jenkins.fornever.me/job/loglist/28/console Somethign with SSH connection. Don't know how to start another one.

**Comment by rexim** [comment]
`/opt/loglist/` contains only `loglist-jvm-1.0-SNAPSHOT.zip` archive which seems to be broken (I can't unpack it)

**Comment by rexim** [comment]
`/opt/loglist/` also contains some logs with exceptions related to Date parsing, but the seems to be old.

**Comment by rexim** [comment]
Building loglist dist locally for a temporary solution...

**Comment by rexim** [comment]
The size of a freshly built dist:
```
-rw-r--r-- 1 rexim rexim  36M февр. 17 13:23 loglist-jvm-1.0-SNAPSHOT.zip
```

The size of the broken one:
```
-rw-rw-r-- 1 loglist loglist  16M февр. 17 02:28 loglist-jvm-1.0-SNAPSHOT.zip
```

**Comment by rexim** [comment]
Renamed `/opt/loglist/loglist-jvm-1.0-SNAPSHOT.zip` to `/opt/loglist/loglist-jvm-1.0-SNAPSHOT.zip.broken`

**Comment by rexim** [comment]
Manually deployed the locally built build. Everything seems to be working for now.

@ForNeVeR, please investigate this when you get a chance. Thanks!

**Comment by ForNeVeR** [comment]
That really was a network failure or an SSH-related error. I've set it up to mark builds such this as failed in future. No issue here.

Just redeployed the build through Jenkins and it's okay.

**Comment by rexim** [comment]
Good!
