### ISSUE TITLE
What's the license of LogList?

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#159]
Derived from https://github.com/codingteam/loglist/pull/158#discussion_r59432534

[LICENSE](https://github.com/codingteam/loglist/blob/10ac8bcce278c9cc47485e7984db1e88e9f0de50/LICENSE) says it's  Apache 2 license, but it was just a part of Play framework template and I didn't think about licensing at the moment. Should we really use this license? I would like to switch to MIT. What do you guys think?

**Comment by ForNeVeR** [comment]
I think that we should change the license. I suggest we ask other contributors (@Minoru, @kosc, @eaeee, @Newlifer) if they are okay with changing the license to MIT.

I also assume that they're okay with changing the license if they'll not complain about it in, say, 5 days.

**Comment by hagane** [comment]
How about ABRMS License?
![](http://www.gifanimados.com/Gifs-Peliculas-Cine/Animaciones-Cine-De-Animacion/Shrek/Asno-Feliz-74297.gif)

**Comment by ForNeVeR** [comment]
I do not care about RMS and don't want the name of this man to be mentioned anywhere near my contributions or our license/legal policy.

**Comment by Minoru** [comment]
I'm okay with my contributions being distributed under the MIT license.

**Comment by Newlifer** [comment]
I second this^W MIT license suggestion. But how about BSD-3?

**Comment by ForNeVeR** [comment]
Useful discussion: http://programmers.stackexchange.com/questions/82321/why-do-people-pick-the-mit-license-over-bsd-if-bsds-non-endorsement-clause-i

But I still prefer MIT.

**Comment by ForNeVeR** [comment]
As a (wannabe?) scientific institution, we tend to prefer MIT in all of our major projects: [horta](https://github.com/codingteam/horta-hell/blob/develop/LICENSE.md), [naggum](https://github.com/codingteam/naggum/blob/develop/License.md), [pacmacs](https://github.com/codingteam/pacmacs.el/blob/master/LICENSE.md). Consider that as our general policy.

I wouldn't turn from it without very solid reason, and currently I'm not seeing it.

**Comment by hagane** [comment]
Language, Doktor! We are **the** scientific institution. Anyone doubting that is a heretic, mutant and/or filthy xenos.

**Comment by rexim** [comment]
@ForNeVeR I believe it's been already 5 days. Are we gonna wait more?

**Comment by ForNeVeR** [comment]
Well, I think we have an approvement from most of the contributors, so we can change the license to MIT.
