### ISSUE TITLE
Enable HTTPS for the whole site

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#168]
Today we have [Let's Encrypt](https://letsencrypt.org/), so we could easily solve the problems like #73 by simply using HTTPS for everything.

@rexim, what would you say? I think I can set it up.

**Comment by rexim** [comment]
Includes #73

I'm ok with that. Thanks!

**Comment by ForNeVeR** [comment]
Okay, I'll set it up and notify you.

**Comment by ForNeVeR** [comment]
Done. Read further story at https://github.com/codingteam/horta-hell/issues/397, https://github.com/codingteam/horta-hell/pull/398, https://github.com/codingteam/horta-foundation/issues/35.

**Comment by Newlifer** [comment]
I second this.
