### ISSUE TITLE
Social metadata

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#170]
Hello, I am Friedrich, and I am ~~sociopath~~ let's say an extremely social guy - I use the shitty social networks all the fucking day instead of doing any real work.

Whenever I copy-paste the loglist quote link such as https://loglist.net/quote/8070 to my Skype, Facebook, Vkontakte or some another shitty goddamn thing, I want it to turn into a glorious image containing an actual quote text if that's possible at all.

We could do it by generating images and inserting their URLs to `<meta property="og:image">`, `<link rel="image_src">` and some shitty web goddamn things like that. You, smarty computer guys, will have to figure that out - I know, you're good at that shit.

### Scope of this issue

- Add `og:title`, `og:type`, `og:image`, `og:description` and `og:url` meta properties to the pages with quotes.
- `og:description` should contain the whole quote text.
- `og:image` should be the URL of the static image representing Loglist in all of its **glory**.

Reference spec: http://opengraphprotocol.org/

**Comment by Minoru** [comment]
Does it have to be an image? Can't we use "og:description" and put the whole text in there?

**Comment by ForNeVeR** [comment]
Will the `og:description` text be rendered by goddamn social thingies?

**Comment by Minoru** [comment]
I have no idea, I don't use any of them. The property is in [the spec](http://opengraphprotocol.org/), though.

**Comment by Minoru** [comment]
Now, now, @rexim, no need to display your butthurt *that* much.

**Comment by rexim** [comment]
Let's limit the scope of this issue to Skype, Slack, Facebook and VK and make sure the link looks good on those. So the exact meta stuff will depend on those. If in the future something will not look good on something else it will be a separate issue.

**Comment by Minoru** [comment]
You forget about Twitter. Or don't you?

**Comment by ForNeVeR** [comment]
I've experimented with http://bash.im/quote/440434
They use `og:description` with the quote text and some static `og:image`. It looks fine (with actual text and shits) within facebook and vkontakte, but looks poorly in Skype and Twitter.

Image would look fine everywhere for the small texts. I've been noticing that people like to share images much more than links to some texts.

**Comment by rexim** [comment]
> You forget about Twitter. Or don't you?

I meantioned Twitter in the last sentence.

**Comment by rexim** [comment]
For an image we need some sort of a logo. I can take that.

**Comment by Minoru** [comment]
I'd like to make a stand here: *images with text are dumb*. It's just unnatural to render text with images. (True, it has been done before, but it was done due to technical limitations.)

If that wasn't enough, images deteriorate quickly when scaled (both up and down). And even if scaling don't kill legibility, the size of the type will: it might be too small to read, or it might be so large it's just hideous.

So I vote for `og:image` with a nice logo and `og:description` with actual text (and we *totally should* use [pilcrows](https://en.wikipedia.org/wiki/Pilcrow) in the latter!)

**Comment by ForNeVeR** [comment]
Check http://stackoverflow.com/questions/35588360/how-to-make-skype-friendly-links-preview-image-tags as a reference of tags that maybe needs to be implemented.

**Comment by ForNeVeR** [comment]
Summary: check the title post, I've updated it and created additional tasks.

**Comment by ForNeVeR** [comment]
Yep it's done, QA finished finally.
