### ISSUE TITLE
Multiple images for social metadata

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#177]
Extracted from https://github.com/codingteam/loglist/pull/176#discussion_r72796247

**Comment by ForNeVeR** [comment]
Check that: https://indieweb.org/The-Open-Graph-protocol#Does_not_support_SVG_images - the URL says it all :(

**Comment by rexim** [comment]
You wanna close that then?

**Comment by ForNeVeR** [comment]
Yes I do wanna close this.

**Comment by rexim** [comment]
Too late! Ha-ha!

**Comment by ForNeVeR** [comment]
:crying_cat_face:
