### ISSUE TITLE
Absolute reverse routed URLs  use HTTP instead of HTTPS

### ISSUE THREAD

**Issue by Minoru** [codingteam/loglist#182]
Even though we're using HTTPS throughout the site, Open Graph metadata uses HTTP in the URLs:

```
<meta property="og:image" content="http://loglist.net/assets/images/gear_400x400.png" />
<meta property="og:url" content="http://loglist.net/quote/8070" />
```

**Comment by rexim** [comment]
The suggested quotes management URLs are not https too. I think this is related to how Play Framework reverse routes absolute URLs. I'll take a look into that.

**Comment by rexim** [comment]
https://loglist.net/feed.rss uses the same mechanism. So we have to keep in mind that if we fix that RSS readers may think that there are lots of new entries or something

**Comment by ForNeVeR** [comment]
Maybe we should set up our nginx so it'll pass original URL to Play framework.

**Comment by ForNeVeR** [comment]
Check [this](http://blog.papauschek.com/2013/10/play-framework-https-nginx/) as a reference nginx configuration (see `X-Forwarded-Proto` and its usage on the Play side) and [this](http://stackoverflow.com/questions/28249822/playframework-return-absolute-url-in-http-instead-of-https) as a guide to preparing proper HTTPS URIs (`absoluteURL(request.secure(), request.host())` or something like this seems to do the trick).

**Comment by rexim** [comment]
@ForNeVeR sounds legit. Thanks!

**Comment by ForNeVeR** [comment]
I think we've applied the proposed solution long ago. Right now it definitely works on 2.0.0-pre2 deployed to the production server. Closing.
