### ISSUE TITLE
Favicon img element must have an alt attribute

### ISSUE THREAD

**Issue by Newlifer** [codingteam/loglist#188]
[Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Floglist.net%2F)

**Comment by ForNeVeR** [comment]
We could also add `lang="ru"` to calm down the validator.

**Comment by Newlifer** [comment]
Sure.

**Comment by rexim** [comment]
@ForNeVeR could you please deploy #189

**Comment by ForNeVeR** [comment]
Done.

**Comment by rexim** [comment]
Verified. Validator says "Document checking completed. No errors or warnings to show." Hence closing the issue.
