### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#191]
https://loglist.net/ is returning 502 at the moment

**Comment by ForNeVeR** [comment]
[![fuck](https://img.youtube.com/vi/qyrJUKC3L-U/maxresdefault.jpg)](https://youtu.be/qyrJUKC3L-U)

That's because of #140. After the maintenance reboot of the host machine the site wasn't started automatically.

**Comment by ForNeVeR** [comment]
So, well, I've started the service manually. The root problem should be fixed in #139.
