### ISSUE TITLE
Cannot post the quote

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#192]
Today I was trying to post the same quote three times in a row:

```
* ħ вошёл в комнату
<ħ> господа
<ħ> помогите с autoconf и libtool
<Minoru> сейчас все в чате поделились на две категории: одна не знает про autotools, а вторая знает и потому притворяется отсутствующей за компом :)
```

All three times, the POST request was terminated due to timeout. Everything else seems to work. Need to verify and investigate.

**Comment by rexim** [comment]
I just realized that I don't know if loglist has any logs. Does it? :D

**Comment by ForNeVeR** [comment]
I bet it have its logs stored by upstart somewhere near `/var/log/upstart/loglist.log`.

**Comment by ForNeVeR** [comment]
I suspect these were my own network issues. Now (after rebooting my network infrastructure) I was able to post the quote without problems.

The logs are completely empty.
