### ISSUE TITLE
Problems initializing DB on a new instance

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#198]
@kosc complains about DB initialization process. He told me that his DB was somehow created without `suggested_quote.token` field, and that caused troubles in loglist.

I suspect that something's wrong with the latest Play we're using, so I'll investigate.

**Comment by rexim** [comment]
@kosc please provide detailed instructions for reproduction.

**Comment by kosc** [comment]
@rexim just deactivate pgcrypto extension. I think it's not a bug, because README.md told me that I need to install pgcrypto, and I ignored it.

**Comment by ForNeVeR** [comment]
Probably some of our migrations/evolutions are not transactional?

**Comment by rexim** [comment]
@ForNeVeR how transactionality affects kosc's ability to focus on documentation? Please proceed, I'm really curious. :)

**Comment by ForNeVeR** [comment]
@rexim here's my hypothesis:

1. @kosc had problems installing `pgcrypto` on his database instance, so he ran evolutions without `pgcrypto` available.
2. [That evolution statement](https://github.com/codingteam/loglist/blob/7064616d497de5b8231df83e9246b8100e8dd6ca/scalajvm/conf/evolutions/default/6.sql#L8-L10) failed.
3. But the whole evolution 6 wasn't rolled back or somehow marked as failed for some reason.
4. [The next evolution 7](https://github.com/codingteam/loglist/blob/7064616d497de5b8231df83e9246b8100e8dd6ca/scalajvm/conf/evolutions/default/7.sql) was successfully applied.

That's the only event sequence I can imagine that could lead to table `suggested_quote` in the database, but without the `token` field. That's why I currently think that we (or the Play framework itself) lack transactionality in its evolution engine. Or maybe something's wrong with that script or PostgreSQL, I don't currently know.

**Comment by rexim** [comment]
@ForNeVeR cool thanks! Now this issue has a pretty well defined scope.
