### ISSUE TITLE
Add quote posting API

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#207]
### MOTIVATION DIVISION.

We've discussed the integration questions with @leha-bot and have agreed on the following implementation to integrate loglist with [@xthon channel](https://t.me/xthon) in Telegram.

### IMPLEMENTATION DIVISION.

1. Add a new API to post the quote to server. Posted quote should be initially unapproved. API should require secret token to be posted.
2. Add a new field to the quotes: `source`. The field should be automatically filled when posting the quote. Pairs "API Token → Source" should be kept in the database.
3. When returning any quotes from the external API, add the `source` field to them.
4. Tag the quotes with source on the UI.

### END PROGRAM.

**Comment by rexim** [comment]
Probably supersedes #100

**Comment by ForNeVeR** [comment]
Oh my. You have done [a lot of work](https://github.com/codingteam/loglist/compare/feature/auto-fill-submit-form-100) on #100.

I don't think it completely supersedes #100. In #100, we wanted to create a full bot-controlled API to post the quotes. But here, we're creating API of another sort: the one that will accept already prepared quotes without need to manually change them by the authors.

**Comment by rexim** [comment]
@ForNeVeR I don't plan to finish that work in the near future. Feel free to drop that branch if needed.
