### ISSUE TITLE
Suggested quotes spam

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#218]
Recently we started to recieve spam in suggested quotes, which suggests that somehow spammers bypass our CAPTCHA. I heard that some time ago somebody found a way to trick that "I'm not a robot" CAPTCHA (cannot find the link though).

Does anybody have any suggestions to improve our spam protection?

**Comment by ForNeVeR** [comment]
> somebody found a way to trick that "I'm not a robot" CAPTCHA (cannot find the link though)

Here it is: https://youtu.be/fsF7enQY8uI

**Comment by ForNeVeR** [comment]
Recaptcha admin panel tells me the following:
![image](https://user-images.githubusercontent.com/92793/36351243-740047e4-14d9-11e8-918a-a1b43a205678.png)

"our developer site" link leads to [this page](https://developers.google.com/recaptcha/docs/verify#api-request) (and it has no useful info), all the graphs are empty and "Download Analytics" button downloads an empty CSV file. Nice.

**Comment by rexim** [comment]
@ForNeVeR welp, I guess the spammers helped us to find a bug :)

**Comment by ForNeVeR** [comment]
Do they actually? I don't think we have a usability bug in our integration. My current theories are:

- either spammers are actively trying to break our recaptcha, and that leads to high amount of (invalid) recaptcha requests: honestly, we probably have about 2 spam quotes and 1 actual quote for the last month, that's not a _bug_ but that's just _true_
- or Google site is just bugged: it thinks we have no traffic and so we have 0/0 = Inf% passage rate

**Comment by rexim** [comment]
> and that leads to high amount of (invalid) recaptcha requests

Can we start counting all of the request on our side to confirm that theory?

**Comment by hagane** [comment]
There's always a possibility that spam quotes are submitted by hand. Do we have raw submission logs or something?

**Comment by hagane** [comment]
BTW, what is the content of spam quotes? Is it generic "Erlang your Postgres" spam, or something more specific?

**Comment by ForNeVeR** [comment]
We have two at the moment:
> 1. It’s exhausting to find knowledgeable people on this matter, but you sound like you know what you’re speaking about! Thanks [and a link to some site here, I won't visit it]
> 2. `<a href=link to the actual site producing cranes>`Мостовые краны производство и изготовление`</a>`

**Comment by rexim** [comment]
> Мостовые краны производство и изготовление

Sounds interesting btw. I might use their service, thanks!

**Comment by ForNeVeR** [comment]
Alright, I've analyzed our logs a bit and it looks like these're human assisted automated requests.

There're not many requests to `POST /quote/new`, but various bots visit our site quite often. I've looked spammers' IP addresses in Google and find that these IPs are registered in multiple so-called "online spam databases".

Not sure if we should take any action at the moment. One interesting thing is that spammers always use HTTP/1.0. Crazy idea: ban it?

**Comment by rexim** [comment]
> Crazy idea: ban it?

I don't like this idea.

> these IPs are registered in multiple so-called "online spam databases".

Can we ban everybody from loglist in these databases?

**Comment by hagane** [comment]
>One interesting thing is that spammers always use HTTP/1.0. Crazy idea: ban it?
I like your way of enforcing progress, herr doctor. But @rexim offered a *saner* solution, methinks.

**Comment by ForNeVeR** [comment]
I believe there're some automated ways of banning addresses based on online IP databases. Maybe fail2ban or something like this?

**Comment by rexim** [comment]
@ForNeVeR I was actually thinking that maybe some of those databases provide some kind of REST API which we could integrate with.

**Comment by ForNeVeR** [comment]
Alright, spam has been stopped by itself. No action required for now.
