### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#3]

**Comment by rexim** [comment]
@ForNeVeR are you going to work on this in the near future? I want to reassign it to myself. =3

**Comment by ForNeVeR** [comment]
Okay, you can take that.

**Comment by rexim** [comment]
Thank you very much, uncle von Never! ^.^

**Comment by rexim** [comment]
I think this issue is too complex. I'd like to convert into a milestone and attach more atomic issues to it.

**Comment by rexim** [comment]
So I've created [REST API](https://github.com/codingteam/loglist/milestones/REST%20API) milestone and attached some tasks to it. Maybe we'll add more in the future. Closing this.

**Comment by ForNeVeR** [comment]
Approved.
