### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#34]

**Comment by ForNeVeR** [comment]
As a

**Comment by ForNeVeR** [comment]
As a self-proclaimed QA I will thoroughly check these shits.

**Comment by rexim** [comment]
@ForNeVeR shit works pretty in my opinion. Do you wanna still check it by yourself?

**Comment by ForNeVeR** [comment]
Yep, I've verified, it's okay.
