### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/loglist#51]
Currently loglist doesn't look very bad on mobile device, but these are some issues with element sizes that should be fixed.

**Comment by Minoru** [comment]
Here's what I got so far:
![screenshot_2016-08-02-03-19-15](https://cloud.githubusercontent.com/assets/118875/17313122/aaae3b88-5861-11e6-9298-8384e582a307.png)

The menus (sorting and filtering) are done, but quotes' headers baffle me.

1. The datetime string is too damn long. If I keep it on the same line as quote ID and rating buttons, the line feels crumpled; if I put it onto a separate line (as shown above), the composition is weird. I believe we could get rid of timestamps on the main page—there's no real use for them there as regulars will remember recent quotes anyway, and newbies will be interested in actual quotes, not post dates. But we should somehow fit the dates on individual quotes' pages, as that stuff is important there (or so I believe).

2. The rating buttons are too small. If I increase their size, they'll  stop forming a proper line with quote ID. Might as well move the buttons someplace else (bash.im does that, placing them under the quote). Unfortunately, such tricks will require code duplication: we'll have to create two voting panels for each quote and then display one or another depending on the device. Insane, but I don't see a way around it short of doing device-detection on the backend (as bash.im does, apparently).

Any ideas on those two fronts will be most appreciated.

**Comment by Minoru** [comment]
Actually, there's a third problem, albeit a much smaller one: should we display RSS icon on mobile? It doesn't fit too well into the footer, effectively requiring a whole line. I think on mobile, people will tend to just copy page's URL and paste it into their feed reader, which will then look at `<link rel="alternate">` to figure out where the feed is.

**Comment by hagane** [comment]
@Minoru That's not half bad!
You can try to put the rating buttons on a separate line and aligning the datetime to the right on a same line with the quote id. That should free up some space while preserving the composition

**Comment by ForNeVeR** [comment]
That looks nice. You could strip timezone and milliseconds part from the time string.

Regarding the RSS icon - it **should** still be usable on mobile. There's no way to *guess* if there's RSS on the site or not. But if the user see RSS icon - he could either click it or copy-paste the site URL to his RSS reader. That's about discoverability.

*(Although I haven't been able to automatically open Loglist's RSS in my feed reader on Android, but that seems to be impossible - bash.im have the same problem on my device.)*

**Comment by hagane** [comment]
@ForNeVeR i believe most browsers do not hand over URI processing based on `Content-Type` header. Consider trying `feed:` (sub)scheme in RSS URI -- AFAIK it's generally recognized, but not in the standards yet.

**Comment by Minoru** [comment]
Okay, here's what I ended up with. I'm pretty happy about the overall look:
![screenshot_2016-08-02-17-14-24](https://cloud.githubusercontent.com/assets/118875/17331786/0d8c21c0-58d5-11e6-85ce-0f20e264187c.png)

I decided not to enlarge the font in the footer—it'll make that stuff draw too much attention. It's readable, but clicking on it is a bit of a challenge:
![screenshot_2016-08-02-17-14-36](https://cloud.githubusercontent.com/assets/118875/17331845/4f491668-58d5-11e6-9da7-31cd52eb5cae.png)

What do you guys think? Should I submit a PR, or is there something else to be done?

**Comment by rexim** [comment]
When in doubt always submit a PR.

**Comment by hagane** [comment]
@Minoru that's great! This placement of rating buttons reflects the attention flow nicely.

**Comment by ForNeVeR** [comment]
I like that.
