### ISSUE TITLE
Migrating to the Celadon Cedar-14 Stack

### ISSUE THREAD

**Issue by rexim** [codingteam/loglist#93]
Currently during deploying the moose we see the following message:

    !   Cedar-10 will reach end-of-life on November 4th, 2015.
    !   Upgrade to Cedar-14 at your earliest convenience.
    !   For more information, check out the following Dev Center article:
    !   https://devcenter.heroku.com/articles/cedar-14-migration

We need to migrate before November 4th, 2015

**Comment by ForNeVeR** [comment]
I don't think we need anything here. Aren't we?

**Comment by rexim** [comment]
It should be closed according to #134

**Comment by ForNeVeR** [comment]
Classified as heresy according to #134. Closed.
